---
subject:    You are the Secret Santaaaa!!!!
message:    "Dear %DEARFROM%!\n\n
  Congratulations! You are the Secret Santa now!\n
  %DEARTO% will be waiting a present from you :)\n
  The date of present is December, 17.\n
  The price of the present should not be more than 1000 RUB.\n
  Happy New Year!!!"
people:
    - name:     Ivan Ivanov
      email:    ivan.ivanov@mail.ru
    - name:     Peter Petrov
      email:    petr.petrov@mail.ru
    - name:     Maria Maryina
      email:    maria.maryina@mail.ru
